# Generated by Django 5.2.4 on 2025-07-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeboard', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='board',
            field=models.CharField(choices=[('team', '팀원 모집'), ('info', '정보 공유'), ('qna', '질문 답변')], default='team', help_text='게시판 종류를 선택하세요', max_length=10),
        ),
    ]
