version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Build started on `date`"
      - sudo dnf -y update
      - sudo dnf -y install python3 python3-pip python3-devel httpd httpd-devel gcc git mariadb105-devel
      - python3 -m venv venv
      - source venv/bin/activate
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Running Django collectstatic"
      - python3 manage.py collectstatic --noinput
artifacts:
  files:
    - '**/*'
    - appspec.yml
    - scripts/**