# Generated by Django 5.2.4 on 2025-07-23 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessscore',
            name='criteria',
            field=models.CharField(choices=[('기획력', '기획력'), ('창의성', '창의성'), ('실현가능성', '실현가능성'), ('완성도', '완성도')], max_length=50),
        ),
        migrations.AlterField(
            model_name='businessscore',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_entry_scores', to='contest.entry'),
        ),
        migrations.AlterField(
            model_name='businessscore',
            name='score',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='contest',
            name='status',
            field=models.CharField(choices=[('모집중', '모집중'), ('심사중', '심사중'), ('종료', '종료')], default='모집중', max_length=20),
        ),
        migrations.AlterField(
            model_name='score',
            name='criteria',
            field=models.CharField(choices=[('기획력', '기획력'), ('창의성', '창의성'), ('실현가능성', '실현가능성'), ('완성도', '완성도')], max_length=50),
        ),
        migrations.AlterField(
            model_name='score',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_scores', to='contest.entry'),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.PositiveIntegerField(),
        ),
    ]
