# Generated by Django 5.2.4 on 2025-07-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_alter_businessscore_criteria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/'),
        ),
    ]
