# Generated by Django 5.2.4 on 2025-07-28 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_alter_contest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='score_type',
            field=models.CharField(choices=[('user', '일반심사'), ('business', '사업자심사')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='contest',
            name='status',
            field=models.CharField(choices=[('대기중', '대기중'), ('모집중', '모집중'), ('심사중', '심사중'), ('종료', '종료')], default='대기중', max_length=20),
        ),
        migrations.AlterField(
            model_name='score',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='contest.entry'),
        ),
        migrations.AlterField(
            model_name='score',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='BusinessScore',
        ),
    ]
