# Generated by Django 5.2.4 on 2025-08-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_remove_userprofile_user_savedcontest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contest_images/'),
        ),
    ]
