# Generated by Django 5.2.4 on 2025-07-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_entry_submission_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='agency',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
