# Generated by Django 4.2.13 on 2025-08-01 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_remove_userprofile_user_savedcontest_and_more'),
        ('contest', '0004_contest_agency_contest_category_and_more'),
    ]

    operations = [
    ]
