# Generated by Django 5.2.4 on 2025-07-28 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_contest_agency_contest_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='status',
            field=models.CharField(choices=[('대기중', '대기중'), ('모집중', '모집중'), ('심사중', '심사중'), ('종료', '종료')], default='대기중’', max_length=20),
        ),
    ]
