# Generated by Django 5.2.4 on 2025-07-25 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('d_day', models.CharField(blank=True, max_length=10)),
                ('image', models.ImageField(upload_to='poster_images/')),
                ('organization', models.CharField(max_length=100)),
                ('company_type', models.CharField(default='-', max_length=100)),
                ('target', models.CharField(max_length=100)),
                ('prize', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('website', models.URLField()),
                ('benefits', models.TextField(default='-')),
                ('category', models.TextField(default='-')),
                ('extra', models.TextField(default='-')),
                ('description', models.TextField(default='-')),
                ('detail_image', models.ImageField(blank=True, null=True, upload_to='poster_details/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
