# Generated by Django 5.2.4 on 2025-07-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0003_poster_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='category_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
