# Generated by Django 5.2.4 on 2025-08-05 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('d_day', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='poster_images/')),
                ('organization', models.CharField(max_length=100)),
                ('company_type', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=100)),
                ('prize', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('website', models.URLField()),
                ('benefits', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('extra', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
    ]
