# Generated by Django 5.2.4 on 2025-07-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='poster',
            name='detail_image',
        ),
        migrations.AlterField(
            model_name='poster',
            name='benefits',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='poster',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='poster',
            name='company_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='poster',
            name='d_day',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='poster',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='poster',
            name='extra',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poster',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
