# Generated by Django 5.2.4 on 2025-08-05 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='status',
            field=models.CharField(choices=[('진행중', '진행중'), ('마감', '마감')], default='진행중', max_length=20),
        ),
    ]
