# Generated by Django 5.2.4 on 2025-07-25 06:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0002_remove_poster_created_at_remove_poster_detail_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
