# Generated by Django 4.2.23 on 2025-07-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0004_poster_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
