# Generated by Django 4.2.23 on 2025-07-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0005_alter_poster_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='image',
            field=models.ImageField(upload_to='poster_images/'),
        ),
    ]
