# Generated by Django 5.2.4 on 2025-07-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0006_alter_poster_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
