# Generated by Django 5.2.4 on 2025-08-08 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0007_poster_views'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE poster_poster DROP COLUMN status;",
            reverse_sql="ALTER TABLE poster_poster ADD COLUMN status varchar(20) NOT NULL DEFAULT 'ONGOING';"
        ),
    ]