# Generated by Django 5.2.4 on 2025-08-08 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0008_remove_status_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
